version: '3.8'
services:
  web:
    build: .
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --log-level debug
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.tasks.worker worker --loglevel=info
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A app.core.celery_app beat --loglevel=info
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"