"""add verification_code to users

Revision ID: 1bcbe5dfd8d4
Revises: b1fca81a9ae2
Create Date: 2025-06-23 12:50:43.954545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcbe5dfd8d4'
down_revision: Union[str, Sequence[str], None] = 'b1fca81a9ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
