"""add verification fields to users model

Revision ID: 74fa1b0b9e3b
Revises: 1bcbe5dfd8d4
Create Date: 2025-06-23 07:52:27.435729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fa1b0b9e3b'
down_revision: Union[str, Sequence[str], None] = '1bcbe5dfd8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
