"""add verification fields to users

Revision ID: b1fca81a9ae2
Revises: 2a8eae7cc1ad
Create Date: 2025-06-23 07:50:11.683625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1fca81a9ae2'
down_revision: Union[str, Sequence[str], None] = '2a8eae7cc1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_expiry')
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###
